/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 01/02/2024
TITULO: QUANTITATIVO DE ATENDIMENTOS
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT
  Count(*) TOTAL,
  DT

FROM(
SELECT
  Count(*) TOTAL,
  To_Char(DT_ATENDIMENTO,'MM/YYYY') DT

FROM
  DBAMV.ATENDIME A,
  DBAMV.LEITO L

WHERE
      A.CD_LEITO = L.CD_LEITO
  AND A.DT_ATENDIMENTO BETWEEN To_Date('01012023','DDMMYYYY')
                            AND To_Date('31082023','DDMMYYYY')
  AND L.CD_UNID_INT = 26

GROUP BY To_Char(DT_ATENDIMENTO,'MM/YYYY'),CD_ATENDIMENTO
     )
GROUP BY DT

ORDER BY DT
;
