SELECT  'ALTER SYSTEM KILL SESSION'||' '''||S.SID || ',' || S.SERIAL# || '''' || '; COMMIT;' SCRIPT,
        S.SID,
        S.SERIAL#,
		LO.ORACLE_USERNAME
FROM    GV$LOCKED_OBJECT LO,
        GV$SESSION S
WHERE   LO.ORACLE_USERNAME = S.USERNAME
GROUP BY S.SID,
        S.SERIAL#,
		LO.ORACLE_USERNAME,
		'ALTER SYSTEM KILL SESSION'||' '''||S.SID || ',' ||''' ' || S.SERIAL# || '''',
		LO.SESSION_ID
ORDER BY LO.SESSION_ID DESC		
		
