SELECT DISTINCT
	   CASE
                  WHEN  RF.SN_FECHADA = 'S' AND CR.DT_EMISSAO IS NOT NULL AND ICR.TP_QUITACAO = 'C'
                    THEN 'CONTA RECEBIDA  - QUITACAO COMPROMETIDA'
                  WHEN  RF.SN_FECHADA = 'S' AND CR.DT_EMISSAO IS NOT NULL AND ICR.TP_QUITACAO = 'V'
                    THEN 'CONTA RECEBIDA  - QUITACAO PREVISTA'
                  WHEN  RF.SN_FECHADA = 'S' AND CR.DT_EMISSAO IS NOT NULL AND ICR.TP_QUITACAO = 'P'
                    THEN 'CONTA RECEBIDA  - QUITACAO PARCIAL'    
                  WHEN  RF.SN_FECHADA = 'S' AND CR.DT_EMISSAO IS NOT NULL AND ICR.TP_QUITACAO = 'Q'
                    THEN 'CONTA RECEBIDA  - QUITACAO TOTAL'
                  WHEN  RF.SN_FECHADA = 'S' AND CR.DT_EMISSAO IS NOT NULL AND ICR.TP_QUITACAO = 'L'
                    THEN 'CONTA RECEBIDA  - QUITACAO CANCELADA'
                  WHEN  RF.SN_FECHADA = 'S' AND CR.DT_EMISSAO IS NOT NULL AND ICR.TP_QUITACAO = 'R'
                    THEN 'CONTA RECEBIDA  - QUITACAO PROTESTADA'
                  WHEN  RF.SN_FECHADA = 'S' AND CR.DT_EMISSAO IS NOT NULL AND ICR.TP_QUITACAO = 'G'
                    THEN 'CONTA RECEBIDA  - QUITACAO COM GLOSA'                    
                  WHEN  RF.SN_FECHADA = 'S' AND CR.DT_EMISSAO IS NOT NULL
                    THEN  'CONTA RECEBIDA'
                  WHEN  RF.SN_FECHADA = 'S'
                    THEN  'CONTA FECHADA'
				  WHEN  RF.SN_FECHADA = 'N'
					THEN  'CONTA ABERTA'
				  ELSE 'TST'
				END STATUS,
				RF.CD_REG_FAT,
				CR.CD_CON_REC,
				RF.DT_INICIO
				
	   
FROM   DBAMV.REG_FAT RF,
       DBAMV.CON_REC CR,
	   DBAMV.ITCON_REC ICR	   

WHERE  RF.CD_REG_FAT = CR.CD_REG_FAT(+)
  AND  CR.CD_CON_REC = ICR.CD_CON_REC(+)
GROUP BY    RF.CD_REG_FAT,
			CR.CD_CON_REC,
			RF.DT_INICIO,
			RF.SN_FECHADA,
			CR.DT_EMISSAO,
			ICR.TP_QUITACAO
