--CREATED BY JEFFERSON LIMA

SELECT U.DS_UNID_INT UNID_INTERNACAO,
			 L.DS_LEITO LEITO,
			 A.CD_ATENDIMENTO ATENDIMENTO,
			 CI.DS_CID,
			 DECODE(PF.DS_PRO_FAT, '', 'NAO INFORMADO', PF.DS_PRO_FAT) MOT_INT,
			 TO_CHAR(A.DT_ATENDIMENTO, 'DD/MM/YYYY') DT_INTERNACAO,
			 A.CD_PACIENTE PRONTUARIO,
			 
			 --DADOS PACIENTE
			 P.NM_PACIENTE PACIENTE,
			 C.NM_CONVENIO CONVENIO,
			 CID.NM_CIDADE,
			 P.DS_ENDERECO ENDERECO,
			 P.NM_BAIRRO,
			 Decode(P.NR_ENDERECO, '', 'NAO INFORMADO', P.NR_ENDERECO) NR_ENDERECO,
			 Decode(P.NR_FONE, '', 'NAO INFORMADO', P.NR_FONE) TELEFONE,
			 Decode(P.NR_CELULAR, '', 'NAO INFORMADO', P.NR_CELULAR) NR_TELEFONE_02,
			 Decode(P.TP_SEXO, 'M', 'MASCULINO', 'F', 'FEMININO') SEXO,
			 Decode(P.TP_ESTADO_CIVIL,
							'V',
							'VIUVO(A)',
							'S',
							'SOLTEIRO(A)',
							'C',
							'CASADO(A)',
							'I',
							'DIVORCIADO(A)',
							'U',
							'UNIAO ESTAVEL',
							'D',
							'DESQUITADO') ESTADO_CIVIL

	FROM DBAMV.ATENDIME A,
			 DBAMV.PACIENTE P,
			 DBAMV.CONVENIO C,
			 DBAMV.LEITO    L,
			 DBAMV.UNID_INT U,
			 DBAMV.CID      CI,
			 DBAMV.PRO_FAT  PF,
			 DBAMV.CIDADE   CID

 WHERE A.DT_ALTA IS NULL
	 AND A.TP_ATENDIMENTO = 'I'
	 AND U.CD_UNID_INT IN (2, 4, 11)
	 AND C.CD_CONVENIO = 3
			
	 AND A.CD_PACIENTE = P.CD_PACIENTE
	 AND A.CD_CONVENIO = C.CD_CONVENIO
	 AND A.CD_LEITO = L.CD_LEITO
	 AND L.CD_UNID_INT = U.CD_UNID_INT
	 AND A.CD_CID = CI.CD_CID
	 AND A.CD_PRO_INT = PF.CD_PRO_FAT(+)
	 AND P.CD_CIDADE = CID.CD_CIDADE

 ORDER BY 1, 2
