SELECT TO_CHAR(PM.DT_SOLICITACAO,'DD/MM/YYYY') DT,
       PM.CD_ATENDIMENTO,
       PA.NM_PACIENTE,
       PR.NM_MNEMONICO,
       E.DS_ESPECIALID,
       DECODE(A.TP_ATENDIMENTO,'U','URGENCIA E EMERGENCIA','I','INTERNACAO') ORIGEM
       
FROM   PAR_MED PM
       INNER JOIN PRESTADOR PR
       ON PR.CD_PRESTADOR = PM.CD_PRESTADOR_PARECER
       INNER JOIN ATENDIME A
       ON A.CD_ATENDIMENTO = PM.CD_ATENDIMENTO
       INNER JOIN PACIENTE PA
       ON PA.CD_PACIENTE = A.CD_PACIENTE
       INNER JOIN ESPECIALID E
       ON E.CD_ESPECIALID = PM.CD_ESPECIALID
       
WHERE  PR.NM_PRESTADOR LIKE '%%'
AND    TRUNC(PM.DT_SOLICITACAO) BETWEEN TO_DATE('01012024','DDMMYYYY') 
                                    AND TO_DATE('31122024','DDMMYYYY')
 
ORDER BY PM.DT_SOLICITACAO ASC
