SELECT  E.DS_ESPECIALID,
        TO_CHAR(DT_PARECER,'MM/YYYY')DT_PARECER,
        COUNT(E.CD_ESPECIALID)QTD
FROM    DBAMV.PAR_MED PM,
        DBAMV.PRESTADOR P,
        DBAMV.ESPECIALID E,
        DBAMV.ATENDIME A
WHERE   DT_SOLICITACAO BETWEEN TO_DATE('122023','MMYYYY')AND TO_DATE('012024','MMYYYY')
  AND   DT_CANCELAMENTO IS NULL                           
  AND   DS_SITUACAO = 'Realizado'
  AND   A.TP_ATENDIMENTO = 'U'
  AND   P.CD_TIP_PRESTA = '8'
  
  AND   PM.CD_PRESTADOR = P.CD_PRESTADOR
  AND   PM.CD_ESPECIALID = E.CD_ESPECIALID
  AND   PM.CD_ATENDIMENTO = A.CD_ATENDIMENTO
  
GROUP
   BY   E.DS_ESPECIALID,
        TO_CHAR(DT_PARECER,'MM/YYYY')
        ;
