CREATE OR REPLACE TRIGGER TRG_REPASSE_AUTOMATICO_HUMS
  AFTER INSERT ON DBAMV.REPASSE
  FOR EACH ROW
  WHEN (NEW.DS_REPASSE = 'RPAOHUMS')
BEGIN
	INSERT INTO LOG_REPASSE_HUMS(
		CD_REPASSE,
		DT_COMPETENCIA,
		DT_REPASSE,
		DS_REPASSE,
		TP_REPASSE,
		CD_MULTI_EMPRESA,
		SN_CONTABILIZAR
	) VALUES (
		:NEW.CD_REPASSE,
		:NEW.DT_COMPETENCIA,
		:NEW.DT_REPASSE,
		:NEW.DS_REPASSE,
		:NEW.TP_REPASSE,
		:NEW.CD_MULTI_EMPRESA,
		:NEW.SN_CONTABILIZAR
	);

END;
/
