SELECT OS.CD_OS,
	   OS.DS_SERVICO,
	   OS.DT_PEDIDO,
	   OS.TP_SITUACAO,
	   OS.NM_USUARIO,
	   S.NM_SETOR,
	   ME.DS_ESPEC,
	   TP.DS_TIPO_OS,
	   L.DS_LOCALIDADE,
	   O.DS_OFICINA,
	   MS.DS_MOT_SERV,
	   U.NM_USUARIO
  FROM DBAMV.SOLICITACAO_OS OS,
       DBAMV.SETOR S,
	   DBAMV.MANU_ESPEC ME,
	   DBAMV.TIPO_OS TP,
	   DBAMV.LOCALIDADE L,
	   DBAMV.OFICINA O,
	   DBAMV.MOT_SERV MS,
	   DBAMV.ITSOLICITACAO_OS IOS,
	   DBASGU.USUARIOS U
 WHERE OS.CD_SETOR = S.CD_SETOR
   AND OS.CD_ESPEC = ME.CD_ESPEC
   AND OS.CD_TIPO_OS = TP.CD_TIPO_OS
   AND OS.CD_LOCALIDADE = L.CD_LOCALIDADE
   AND OS.CD_OFICINA = O.CD_OFICINA
   AND OS.CD_MOT_SERV = MS.CD_MOT_SERV
   AND OS.CD_OS = IOS.CD_OS
   AND OS.CD_RESPONSAVEL = U.CD_USUARIO
   AND OS.TP_SITUACAO != 'C'
   AND OS.CD_MULTI_EMPRESA = 1
