/*CREATED BY
NAME: ROMILSON SOARES
CARGO: COORDENADOR DE TI
DATA: 25/01/2024
TITULO: VERIFICAÇÃO DE REGISTROS PARA TRIGGER DA NUTRIÇÃO
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPONSÁVEL: JEFFERSON LIMA GONÇALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 25/01/2024
MOTIVO: INSERÇÃO DE COMPARTIVO COM REGISTROS INSERIDOS
DESCRIÇÃO: 
*/

SELECT  SEQ_MOV_CARDAPIO.NEXTVAL AS CD_MOV_CARDAPIO,
        'P' AS TP_CARDAPIO,
        5 AS CD_TIPO_REFEICAO,
        A2.CD_ATENDIMENTO,
        900 AS CD_TIPO_DIETA,
        1 AS CD_COPA,
        25 AS CD_SETOR,
        1 CD_MULTI_EMPRESA,
        SYSDATE AS DT_MOV_CARDAPIO,
        CD_ITPRE_MED
        
FROM   (SELECT *
        FROM   ATENDIME A
        WHERE  A.TP_ATENDIMENTO = 'I'
          AND  A.CD_MULTI_EMPRESA = 1
          AND  A.DT_ALTA IS NULL
       ) A2 INNER JOIN
              (SELECT  PM2.CD_ATENDIMENTO,
                       ITM2.CD_ITPRE_MED
               FROM    PRE_MED PM2,
                       ITPRE_MED ITM2,
                       TIP_PRESC TP2
               WHERE   ITM2.CD_PRE_MED = PM2.CD_PRE_MED
                 AND   TP2.CD_TIP_PRESC = ITM2.CD_TIP_PRESC
                 AND   ITM2.CD_TIP_ESQ = 'DIE'
                 AND   TP2.CD_TIPO_DIETA IS NOT NULL
                 AND   TRUNC(PM2.DT_PRE_MED) = TRUNC(SYSDATE)
              ) A3 ON A3.CD_ATENDIMENTO = A2.CD_ATENDIMENTO

WHERE  A3.CD_ITPRE_MED IN (SELECT  MC.CD_ITPRE_MED
                             FROM    DBAMV.MOV_CARDAPIO MC)
                             
