/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 17/11/2023
TITULO: MOVIMENTAÇÃO DE CARDAPIO PARA PACIENTE
DESCRICAO: MOVIMENTAÇÃO DE CARDAPIO PARA FUNCIONARIOS POR SETOR, POR TIPO DE REFEI��O E POR DIA.
FILTROS:

#TIPO DE CARDAPIO = (F)FUNCIONARIO
#INTERVALO DE DATAS = MÊS E ANO ATUAL   

ÚLTIMA ATUALIZAÇÃO
RESPONSÁVEL: 
CARGO: 
DATA:
MOTIVO:
DESCRIÇÃO: 
*/

SELECT  NM_SETOR,
        DS_TIPO_REFEICAO,
        NM_FUNC,
        COUNT(DS_TIPO_REFEICAO)QTD,
        TO_CHAR(SNK.DT_DIAS,'DD') DATA_R
FROM(   SELECT  S.NM_SETOR,
                MC.CD_MOV_CARDAPIO,
                TR.DS_TIPO_REFEICAO,
                TO_DATE(DT_MOV_CARDAPIO) DT_R1,
                TO_CHAR(DT_MOV_CARDAPIO,'DD/MM/YYYY') DT_R,
                MC.CD_FUNC CD_FUNCIONARIO
        FROM    DBAMV.MOV_CARDAPIO MC,
                DBAMV.TIPO_REFEICAO TR,
                DBAMV.SETOR S
        WHERE   MC.CD_SETOR = S.CD_SETOR
          AND   MC.CD_TIPO_REFEICAO = TR.CD_TIPO_REFEICAO
          AND   MC.TP_CARDAPIO = 'F'  
        ORDER
           BY   CD_MOV_CARDAPIO  
        )F,
        DBAMV.SNK_DT_PD SNK,
        DBAMV.FUNCIONARIO FUN
WHERE   F.DT_R1(+) = SNK.DT_DIAS
  AND   EXTRACT(MONTH FROM SNK.DT_DIAS) = EXTRACT(MONTH FROM SYSDATE)
  AND   EXTRACT(YEAR FROM SNK.DT_DIAS) = EXTRACT(YEAR FROM SYSDATE)
  AND   F.CD_FUNCIONARIO = FUN.CD_FUNC(+)    
GROUP
   BY   TO_CHAR(SNK.DT_DIAS,'DD'),
        NM_SETOR,
        DS_TIPO_REFEICAO,
        NM_FUNC
