/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 17/11/2023
TITULO: MOVIMENTAÇÃO DE CARDAPIO PARA PACIENTE
DESCRICAO: MOVIMENTAÇÃO DE CARDAPIO PARA FUNCIONARIOS POR SETOR, POR TIPO DE REFEIÇÃO E POR DIA.
FILTROS:

#TIPO DE CARDAPIO = (A)ACOMPANHANTE
#INTERVALO DE DATAS = MÊS E ANO ATUAL   

ÚLTIMA ATUALIZAÇÃO
RESPONSÁVEL: 
CARGO: 
DATA:
MOTIVO:
DESCRIÇÃO: 
*/

SELECT  DS_TIPO_REFEICAO,
        SUM(QT_CARDAPIO)QTD,
        TO_CHAR(SNK.DT_DIAS,'DD') DATA_R
FROM(   SELECT  S.NM_SETOR,
                MC.CD_MOV_CARDAPIO,
                TR.DS_TIPO_REFEICAO,
                TO_DATE(DT_MOV_CARDAPIO) DT_R1,
                TO_CHAR(DT_MOV_CARDAPIO,'DD/MM/YYYY') DT_R,
                MC.CD_FUNC CD_FUNCIONARIO,
                IMC.QT_CARDAPIO
        FROM   (SELECT M.CD_SETOR,
                       M.CD_TIPO_REFEICAO,
                       M.TP_CARDAPIO,
                       M.CD_FUNC,
                       M.DT_MOV_CARDAPIO,
                       M.CD_MOV_CARDAPIO,
                       U.CD_USUARIO
                FROM   DBAMV.MOV_CARDAPIO M,
                       DBASGU.USUARIOS U
                WHERE  M.CD_USUARIO_ENTREGA = U.CD_USUARIO(+)) MC,
                DBAMV.TIPO_REFEICAO TR,
                DBAMV.SETOR S,
                DBAMV.ITMOV_CARDAPIO IMC,
                DBAMV.OPCAO_CARDAPIO OC
        WHERE   MC.CD_SETOR = S.CD_SETOR
          AND   MC.CD_TIPO_REFEICAO = TR.CD_TIPO_REFEICAO
          AND   MC.TP_CARDAPIO = 'F'
          AND   MC.CD_MOV_CARDAPIO = IMC.CD_MOV_CARDAPIO(+)
          AND   IMC.CD_OPCAO = OC.CD_OPCAO(+)
          --AND   S.CD_SETOR = 27
          --AND   OC.CD_OPCAO NOT IN  ('165')  
          --AND   {Vfull}
        ORDER
           BY   CD_MOV_CARDAPIO  
        )F,
       (SELECT  TO_DATE(DATA_ATEND) DT_DIAS
        FROM(SELECT  TO_CHAR(DT_ATENDIMENTO,'DD/MM/YYYY') DATA_ATEND
             FROM    DBAMV.ATENDIME A)
        GROUP
           BY   TO_DATE(DATA_ATEND)) SNK,
        DBAMV.FUNCIONARIO FUN
WHERE   F.DT_R1(+) = SNK.DT_DIAS
  AND   EXTRACT(MONTH FROM SNK.DT_DIAS) = EXTRACT(MONTH FROM SYSDATE)
  AND   EXTRACT(YEAR FROM SNK.DT_DIAS) = EXTRACT(YEAR FROM SYSDATE)
  AND   F.CD_FUNCIONARIO = FUN.CD_FUNC(+)    
GROUP
   BY   TO_CHAR(SNK.DT_DIAS,'DD'),
        DS_TIPO_REFEICAO
ORDER
   BY   DATA_R
