/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 13/05/2024
TITULO: RELATÓRIO MATERIAIS E MEDICAMENTOS
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT    DISTINCT
          DECODE(EP.QT_ESTOQUE_ATUAL,NULL,0
                                    ,EP.QT_ESTOQUE_ATUAL) QT_ESTOQUE_ATUAL,
		  P.CD_PRODUTO,
          P.DS_PRODUTO,
          ESP.DS_ESPECIE,
		  UP.DS_UNIDADE,
          E.DS_ESTOQUE,
          IEP.VL_UNITARIO
          
          
FROM      DBAMV.PRODUTO P,
          DBAMV.EST_PRO EP,
          DBAMV.ESTOQUE E,
          DBAMV.ESPECIE ESP,
		  DBAMV.UNI_PRO UP,
          (SELECT    VL_UNITARIO,
		             IEP.CD_PRODUTO,
					 IEP.DT_GRAVACAO
			FROM    (SELECT    MAX(DT_GRAVACAO)DT_ULT,
							   CD_PRODUTO
					 FROM     DBAMV.ITENT_PRO
					 WHERE    DT_GRAVACAO < TO_DATE('25/08/2023','DD/MM/YYYY')	  
					 GROUP BY CD_PRODUTO) T,
			         DBAMV.ITENT_PRO IEP
			WHERE    IEP.CD_PRODUTO = T.CD_PRODUTO
			  AND    IEP.DT_GRAVACAO = T.DT_ULT) IEP
		   
WHERE     P.CD_PRODUTO = EP.CD_PRODUTO
  AND     EP.CD_ESTOQUE = E.CD_ESTOQUE
  AND     P.CD_ESPECIE = ESP.CD_ESPECIE
  AND     P.CD_PRODUTO = UP.CD_PRODUTO
  AND     P.CD_PRODUTO = IEP.CD_PRODUTO
  
  AND     UP.TP_RELATORIOS = 'R'
  AND     UP.SN_ATIVO = 'S'
  AND     P.SN_MOVIMENTACAO = 'S'
  AND     P.SN_BLOQUEIO_DE_COMPRA = 'N'
        
ORDER BY  P.DS_PRODUTO;
