/*CREATED BY
NAME: JEFFERSON LIMA GONÇALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 22/03/2024
TITULO: CONSULTA DE ACESSOS POR TIPO DE PRESTADOR
DESCRICAO: 
FILTROS:

*/

SELECT	P.NM_PRESTADOR,
        U.CD_USUARIO,
        TP.NM_TIP_PRESTA,
        PA.DS_PAPEL,
        PA.CD_PRODUTO,
        M.CD_SISTEMA_DONO,
        M.CD_MODULO

FROM	DBAMV.PRESTADOR P,
        DBASGU.USUARIOS U,
        DBASGU.PAPEL_USUARIOS PU,
        DBASGU.PAPEL_MOD PM,
        DBASGU.PAPEL PA,
        DBASGU.MODULOS M,
        DBAMV.TIP_PRESTA TP

WHERE   P.CD_TIP_PRESTA IN (4,14)
  AND   P.TP_SITUACAO = 'A'
  AND 	P.CD_PRESTADOR = U.CD_PRESTADOR
  AND   U.CD_USUARIO = PU.CD_USUARIO
  AND   PU.CD_PAPEL = PM.CD_PAPEL
  AND   PM.CD_PAPEL = PA.CD_PAPEL	
  AND  	PM.CD_MODULO = M.CD_MODULO
  AND 	P.CD_TIP_PRESTA = TP.CD_TIP_PRESTA
  AND   PM.CD_MODULO IN ('C_PAINEL_LEITOS','C_LEITOS','C_LEITOS_GERENCIAL')
;