/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 21/11/2023
TITULO: MAPA DIÁRIO DA NUTRIÇÃO
DESCRICAO: INFORMAÇÕES SOBRE O MAPA DE NUTRIÇÃO E CONFIRMAÇÃO DE ENTRAGA DA COPA
FILTROS:

#SOMENTE PACIENTES INTERNADOS = SIM
#UNIDADE DE INTERNACAO
#TIPO DE ATENDIMENTO = INTERNAÇÃO

ÚLTIMA ATUALIZAÇÃO
RESPONSÁVEL: 
CARGO: 
DATA:
MOTIVO:
DESCRIÇÃO: 
*/

SELECT  L.DS_LEITO,
        P.NM_PACIENTE,
        FN_IDADE(P.DT_NASCIMENTO,'a A',SYSDATE)IDADE,
        TD.DS_TIPO_DIETA,
        A.CD_ATENDIMENTO,
        SUM(CASE
          WHEN MC.CD_TIPO_REFEICAO = '1'
            THEN 1
          ELSE NULL
              END) D,
        SUM(CASE
          WHEN MC.CD_TIPO_REFEICAO = '3'
            THEN 1
              END) A,
        SUM(CASE
          WHEN MC.CD_TIPO_REFEICAO = '9'
            THEN 1
          ELSE NULL
              END) L,
        SUM(CASE
          WHEN MC.CD_TIPO_REFEICAO = '5'
            THEN 1
             END) J,  
        SUM(CASE
          WHEN MC.CD_TIPO_REFEICAO = '6'
            THEN 1
          ELSE NULL
              END) C,               
        DECODE(A.SN_ACOMPANHANTE,'S','SIM'
                                ,'N','NAO')ACOMPANHANTE,
        MC.DS_OBSERVACAO                        
FROM    DBAMV.LEITO L,
        DBAMV.PACIENTE P,
        DBAMV.ATENDIME A,
        DBAMV.MOV_CARDAPIO MC,
        DBAMV.TIPO_DIETA TD,
        DBAMV.TIPO_REFEICAO TR
WHERE   A.CD_PACIENTE = P.CD_PACIENTE
  AND   A.CD_LEITO = L.CD_LEITO(+)        
  AND   A.CD_ATENDIMENTO = MC.CD_ATENDIMENTO
  AND   MC.CD_TIPO_DIETA = TD.CD_TIPO_DIETA
  AND   MC.CD_TIPO_REFEICAO = TR.CD_TIPO_REFEICAO
  AND   EXTRACT(MONTH FROM MC.DT_MOV_CARDAPIO) = EXTRACT(MONTH FROM A.DT_ATENDIMENTO)
  AND   EXTRACT(DAY FROM MC.DT_MOV_CARDAPIO)  = EXTRACT(DAY FROM A.DT_ATENDIMENTO)
  AND   A.DT_ALTA IS NULL
  AND   A.TP_ATENDIMENTO = 'I'
  AND   L.CD_UNID_INT IN ('26')
GROUP
   BY   L.DS_LEITO,
        P.NM_PACIENTE,
        FN_IDADE(P.DT_NASCIMENTO,'a A',SYSDATE),
        TD.DS_TIPO_DIETA,
        A.SN_ACOMPANHANTE,
        A.CD_ATENDIMENTO,
        MC.DS_OBSERVACAO;
        
