SELECT
  Decode(HSP.SN_ATIVO,
                    'S','ATIVO',
                    'N','INATIVO') STATUS,
  Decode(HSP.TP_ALERGIA
                       ,'A','ALIMENTO'
                       ,'S','MEDICAMENTO'
                       ,'O','OUTROS'
                       ,HSP.TP_ALERGIA) SUBSTANCIA,
  Decode(HSP.TP_SEVERIDADE,
                         'G','GRAVE',
                         'M','MODERADA',
                         'L','LEVE',
                         'D','DESCONHECIDA',
                         HSP.TP_SEVERIDADE) SEVERIDADE,

  Decode(S.DS_SUBSTANCIA,
                        '',HSP.DS_ALERGIA,
                        S.DS_SUBSTANCIA) DESCRICAO,
  HSP.DS_AVISO OBSERVACAO,
  To_CHAR(HSP.DH_CRIACAO,'DD/MM/YYYY') DATA_INCLUSAO

FROM
  DBAMV.ATENDIME A,
  DBAMV.PACIENTE P,
  DBAMV.HIST_SUBS_PAC HSP,
  DBAMV.PW_ALERGIA_PACIENTE PAP,
  DBAMV.SUBSTANCIA S

WHERE
      A.CD_PACIENTE = P.CD_PACIENTE
  AND A.CD_PACIENTE = HSP.CD_PACIENTE
  AND HSP.CD_HIST_SUBS_PAC = PAP.CD_HIST_SUBS_PAC
  AND HSP.CD_SUBSTANCIA = S.CD_SUBSTANCIA(+)

  -- AND A.CD_ATENDIMENTO = --CODIGO DO ATENDIMENTO

GROUP BY
  P.CD_PACIENTE,
  HSP.SN_ATIVO,
  S.DS_SUBSTANCIA,
  HSP.TP_SEVERIDADE,
  DS_AVISO,
  DS_ALERGIA,
  HSP.TP_ALERGIA,
  HSP.DH_CRIACAO

ORDER BY
  P.NM_PACIENTE;
