SELECT
  F1.CD_CID,
  F1.DS_CID,
  F1.TP_SITUACAO,
  F1.POSICAO

FROM(
  SELECT
    CD_CID,
    DS_CID ||' '|| Decode(RN,'1','(NEW)',
                       RN,'(OLD)') DS_CID,
    TP_SITUACAO,
    'PRINCIPAL' POSICAO,
    CD_DIAGNOSTICO_ATENDIME,
    CD_ATENDIMENTO

  FROM (
    SELECT
      A.CD_ATENDIMENTO,
      C.CD_CID,
      C.DS_CID,
      DA.TP_SITUACAO,
      DC.DH_FECHAMENTO,
      DA.CD_DIAGNOSTICO_ATENDIME,
      ROW_NUMBER() OVER (PARTITION BY A.CD_ATENDIMENTO ORDER BY DC.DH_FECHAMENTO DESC) AS rn
    FROM
      DBAMV.ATENDIME A,
      DBAMV.DIAGNOSTICO_ATENDIME DA,
      DBAMV.CID C,
      DBAMV.PW_DOCUMENTO_CLINICO DC


    WHERE
      A.CD_ATENDIMENTO = DA.CD_ATENDIMENTO
      AND DA.CD_CID = C.CD_CID
      AND DA.CD_DOCUMENTO_CLINICO = DC.CD_DOCUMENTO_CLINICO

    ORDER BY
      DC.DH_FECHAMENTO DESC

    ) S
  WHERE
  --      RN = 1

  -- Par�mentro de atendimento 01
     CD_ATENDIMENTO = 1174009
    )F1


--
UNION ALL
--


SELECT
    F1.CD_CID,
    F2.DS_CID,
    F1.TP_SITUACAO,
    F1.POSICAO
FROM (
  SELECT
    C.CD_CID,
    C.DS_CID,
    DA.TP_SITUACAO,
    'SECUNDARIO' POSICAO ,
    DCI.CD_DIAGNOSTICO_ATENDIME,
    DCI.CD_ATENDIMENTO

  FROM
    DBAMV.PW_DIAGNOSTICO_ATENDIME_CID DCI,
    DBAMV.CID C,
    DBAMV.DIAGNOSTICO_ATENDIME DA

  WHERE
        DCI.CD_CID = C.CD_CID
    AND DCI.CD_DIAGNOSTICO_ATENDIME = DA.CD_DIAGNOSTICO_ATENDIME

  ORDER BY
    DCI.CD_DIAGNOSTICO_ATENDIME DESC
  )F1,
  (
  SELECT
    CD_CID,
    DS_CID ||' '|| Decode(RN,'1','(NEW)',
                       RN,'(OLD)') DS_CID,
    TP_SITUACAO,
    CD_DIAGNOSTICO_ATENDIME,
    CD_ATENDIMENTO

  FROM (
    SELECT
      A.CD_ATENDIMENTO,
      C.CD_CID,
      C.DS_CID,
      DA.TP_SITUACAO,
      DC.DH_FECHAMENTO,
      DA.CD_DIAGNOSTICO_ATENDIME,
      ROW_NUMBER() OVER (PARTITION BY A.CD_ATENDIMENTO ORDER BY DC.DH_FECHAMENTO DESC) AS rn
    FROM
      DBAMV.ATENDIME A,
      DBAMV.DIAGNOSTICO_ATENDIME DA,
      DBAMV.CID C,
      DBAMV.PW_DOCUMENTO_CLINICO DC


    WHERE
      A.CD_ATENDIMENTO = DA.CD_ATENDIMENTO
      AND DA.CD_CID = C.CD_CID
      AND DA.CD_DOCUMENTO_CLINICO = DC.CD_DOCUMENTO_CLINICO

      AND A.CD_ATENDIMENTO = 1174009

    ORDER BY
      DC.DH_FECHAMENTO DESC

    ) S
  --WHERE
    --    RN = 1
  )F2

WHERE
    F1.CD_DIAGNOSTICO_ATENDIME = F2.CD_DIAGNOSTICO_ATENDIME

-- Par�mentro de atendimento 02
AND F1.CD_ATENDIMENTO = 1174009
;
