SELECT  IRF.CD_PRO_FAT CD_PRO_FAT,
        PF.DS_PRO_FAT,
        CASE
          WHEN IRF.SN_PERTENCE_PACOTE = 'S'
            THEN 'PACOTE'
          ELSE 'EXTRA'
            END TP_PROCEDIMENTO,
        SUM(IRF.QT_LANCAMENTO) QUANTITATIVO,
        IRF.VL_UNITARIO,
        SUM(IRF.VL_TOTAL_CONTA)
FROM    DBAMV.ITREG_FAT IRF,
        DBAMV.REG_FAT RF,
        DBAMV.PRO_FAT PF
WHERE   IRF.CD_REG_FAT = RF.CD_REG_FAT
  AND   IRF.CD_PRO_FAT = PF.CD_PRO_FAT
  --AND   IRF.CD_GRU_FAT NOT IN (1)
  AND   PF.CD_GRU_PRO NOT IN (56)
  --AND   IRF.TP_PAGAMENTO IN ('C','P')
  AND   IRF.SN_PERTENCE_PACOTE = 'S'
  --AND   PF.SN_PACOTE = 'N'
  AND   RF.CD_ATENDIMENTO = 1288626    
     
GROUP
   BY   PF.DS_PRO_FAT,
        PF.CD_PRO_FAT,
        IRF.SN_PERTENCE_PACOTE,
        --IRF.QT_LANCAMENTO,
        IRF.CD_PRO_FAT,
        IRF.VL_UNITARIO
ORDER
   BY   TP_PROCEDIMENTO,
        PF.DS_PRO_FAT
;        
