/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 01/02/2024
TITULO: SINAIS VITAIS (PCO)
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT
  ISV.VALOR,
  SV.DS_SINAL_VITAL SINAL_VITAL,
  UA.DS_UNIDADE_AFERICAO UNIDADE_MEDIDA,
  To_Char(DC.DH_FECHAMENTO,'DD/MM/YYYY HH24:MI') DATA_HORA

FROM(
    SELECT
      CD_COLETA_SINAL_VITAL,
      CD_ATENDIMENTO
    FROM(
        SELECT
	        ISV.CD_COLETA_SINAL_VITAL,
          CSV.DATA_COLETA,
          CSV.CD_ATENDIMENTO,
          Row_Number() OVER (PARTITION BY CSV.CD_ATENDIMENTO ORDER BY DATA_COLETA DESC) RN
        FROM
	        ITCOLETA_SINAL_VITAL ISV,
	        COLETA_SINAL_VITAL CSV
        WHERE
	            ISV.CD_COLETA_SINAL_VITAL = CSV.CD_COLETA_SINAL_VITAL
        GROUP BY
          ISV.CD_COLETA_SINAL_VITAL,
          CSV.DATA_COLETA,
          CSV.CD_ATENDIMENTO

        ORDER BY CSV.DATA_COLETA DESC
        )
    WHERE
    RN = 1
    )F1,
    DBAMV.ITCOLETA_SINAL_VITAL ISV,
    DBAMV.SINAL_VITAL SV,
    DBAMV.PW_UNIDADE_AFERICAO UA,
    DBAMV.COLETA_SINAL_VITAL CSV,
    DBAMV.PW_DOCUMENTO_CLINICO DC

WHERE
      F1.CD_COLETA_SINAL_VITAL = ISV.CD_COLETA_SINAL_VITAL
  AND SV.CD_SINAL_VITAL = ISV.CD_SINAL_VITAL
  AND ISV.CD_UNIDADE_AFERICAO = UA.CD_UNIDADE_AFERICAO
  AND F1.CD_COLETA_SINAL_VITAL = CSV.CD_COLETA_SINAL_VITAL
  AND CSV.CD_DOCUMENTO_CLINICO = DC.CD_DOCUMENTO_CLINICO

  --Par�metro de pesquisas--
  AND F1.CD_ATENDIMENTO = 1173986
  AND ISV.CD_SINAL_VITAL IN (67,68)
;