/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 25/01/2024
TITULO: AVALIAÇÃO E PARECER X FATURAMENTO (INTERNÇÃO)
DESCRICAO: 
FILTROS:

ULTIMA ATUALIZAÇÃO
RESPONSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT  DISTINCT
        A.CD_ATENDIMENTO ATENDIMENTO,
        RF.CD_REG_FAT CONTA_ATEND,
        IRF.CD_PRO_FAT COD_PROCEDIMENTO,
        PF.DS_PRO_FAT DESC_PROCEDIMENTO,
        IRF.VL_TOTAL_CONTA VALOR_PROCEDIMENTO,
        P.NM_PACIENTE NOME_PACIENTE,
        PM.DT_PARECER 

FROM    DBAMV.REG_FAT RF,
        DBAMV.ATENDIME A,
        DBAMV.PACIENTE P,
        DBAMV.ITREG_FAT IRF,
        DBAMV.PRO_FAT PF,
        DBAMV.PAR_MED PM

WHERE   A.CD_ATENDIMENTO = RF.CD_ATENDIMENTO
  AND   A.CD_PACIENTE = P.CD_PACIENTE
  AND   RF.CD_REG_FAT = IRF.CD_REG_FAT
  AND   IRF.CD_PRO_FAT = PF.CD_PRO_FAT
  AND   A.CD_ATENDIMENTO = PM.CD_ATENDIMENTO(+)
  
  AND   RF.CD_CONVENIO IN (3,4)
  AND   IRF.CD_PRO_FAT IN ('10101039','10102019','10102021','10102020')
--  AND   IRF.VL_TOTAL_CONTA IN ('350','315')
--  AND   A.CD_ATENDIMENTO = 1186590

 
--87295
;
