SELECT Y.DS_TAB_FAT,
	   Y.CD_PRO_FAT,
	   Y.DS_PRO_FAT,
	   Y.VL_HONORARIO,
	   Y.VL_OPERACIONAL,
	   Y.VL_TOTAL,
	   Y.DT_VIGENCIA,
	   Z.QTD,
	   P.QT_DIARIAS,
	   P.CD_PRO_FAT CD_PRO_FAT_X_PCT
FROM   (SELECT ITF.CD_PRO_FAT, COUNT(ITF.CD_PRO_FAT) AS QTD
		  FROM ITREG_FAT ITF
		 GROUP BY ITF.CD_PRO_FAT) Z,
		 
	   (SELECT R.DS_REGRA,
			   VP.CD_TAB_FAT,
			   TF.DS_TAB_FAT,
			   VP.CD_PRO_FAT,
			   PF.DS_PRO_FAT,
			   VP.VL_HONORARIO,
			   VP.VL_OPERACIONAL,
			   VP.VL_TOTAL,
			   VP.DT_VIGENCIA
		  FROM VAL_PRO VP, 
		       TAB_FAT TF, 
			   PRO_FAT PF, 
			   ITREGRA IR, 
			   REGRA R
		 WHERE TF.CD_TAB_FAT = VP.CD_TAB_FAT
		   AND PF.CD_PRO_FAT = VP.CD_PRO_FAT
		   AND IR.CD_TAB_FAT = TF.CD_TAB_FAT
		   AND R.CD_REGRA = IR.CD_REGRA
		   AND R.CD_REGRA = 72
		   AND VP.CD_TAB_FAT IN (39)
		   AND VP.DT_VIGENCIA = (SELECT MAX(VP2.DT_VIGENCIA)
		                         FROM VAL_PRO VP2
								 WHERE VP2.CD_PRO_FAT = VP.CD_PRO_FAT
								   AND VP2.CD_TAB_FAT IN (39))
		 ORDER BY 5, 9 ASC) Y,
		 
		 DBAMV.PACOTE P
WHERE Z.CD_PRO_FAT = Y.CD_PRO_FAT
  AND y.CD_PRO_FAT = P.CD_PRO_FAT_PACOTE(+)
ORDER BY Z.QTD DESC
