/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 21/03/2024
TITULO: PEDIDOS DE EXAMES DUPLICADOS
DESCRICAO: 
FILTROS:
*/

SELECT	PR.CD_PED_RX "Cód Ped",
        A.CD_ATENDIMENTO "Atendimento",
        A.TP_ATENDIMENTO "Tipo",
        ER.DS_EXA_RX "Exame",
        P.NM_PACIENTE "Paciente",
        PR.NM_USUARIO "Usuario",
        COUNT(ER.DS_EXA_RX)"Qtd"

FROM	  DBAMV.PED_RX PR,
        DBAMV.ATENDIME A,
        DBAMV.ITPED_RX IPR,
        DBAMV.EXA_RX ER,
        DBAMV.PACIENTE P

WHERE	  PR.CD_ATENDIMENTO  = A.CD_ATENDIMENTO
  AND 	PR.CD_PED_RX = IPR.CD_PED_RX
  AND	  IPR.CD_EXA_RX =	ER.CD_EXA_RX
  AND   A.CD_PACIENTE = P.CD_PACIENTE
  AND   A.CD_MULTI_EMPRESA = 1
  AND   PR.DT_PEDIDO BETWEEN TO_DATE('01122023','DDMMYYYY') AND TO_DATE('31032024','DDMMYYYY')
  
GROUP
   BY	  A.CD_ATENDIMENTO,
        ER.DS_EXA_RX,
        PR.CD_PED_RX,
        P.NM_PACIENTE,
        A.TP_ATENDIMENTO,
        PR.NM_USUARIO       

HAVING 	COUNT(A.CD_ATENDIMENTO) > 1

ORDER
   BY	PR.CD_PED_RX DESC
;
