/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 01/02/2024
TITULO: TAXA DE EXAMES RADIOLOGICOS CANCELADOS MENSALMENTE
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT  F1.TOTAL TOTAL_PED_EX
       ,F2.TOTAL
       ,F1.DATA

FROM(SELECT  Count(PEDIDO) TOTAL
       ,DATA

FROM(
SELECT CD_PED_RX PEDIDO
      ,To_Char(DT_EXCLUSAO,'MM/YYYY') DATA

FROM DBAMV.LOG_EXC_EXA_RX

WHERE DT_EXCLUSAO IS NOT NULL
AND   DT_EXCLUSAO BETWEEN To_Date('01/01/2023','DD/MM/YYYY')AND
                          To_Date('31/07/2023','DD/MM/YYYY')
)

GROUP BY DATA
)F1
,
(SELECT  Count(*)TOTAL
       ,To_Char(DT_PEDIDO,'MM/YYYY')DATA

FROM    DBAMV.PED_RX PR

WHERE   DT_PEDIDO BETWEEN To_Date('012023','MMYYYY') AND To_Date('072023','MMYYYY')

GROUP BY To_Char(DT_PEDIDO,'MM/YYYY'))F2

WHERE F1.DATA = F2.DATA

--11187