/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 01/02/2024
TITULO: QUANTITATIVO DE EXAMES RADIOLOGICOS MENSAIS
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT Count(CD_PED_RX)TOTAL
      ,DATA

FROM (

SELECT PR.CD_PED_RX
      ,To_Char(PR.DT_PEDIDO,'MM/YYYY') DATA

FROM DBAMV.ITPED_RX IR
    ,DBAMV.PED_RX PR

WHERE IR.CD_PED_RX = PR.CD_PED_RX
AND   IR.DT_REALIZADO IS NOT NULL
AND   PR.DT_PEDIDO BETWEEN To_Date('01/01/2023','DD/MM/YYYY') AND To_Date('31/07/2023','DD/MM/YYYY')
AND   PR.CD_SET_EXA IN ('4','7','19')

)

GROUP BY DATA
ORDER BY DATA
--4	RAO - X / HUI
--7	ULTRASONOGRAFIA / HUI
--19	TOMOGRAFIA COMPUTADORIZADA HUI
