/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 01/02/2024
TITULO: VISITAS HOSPITALARES
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT  DS_PRODUTO,
        CD_PRODUTO,
        COUNT(CD_PRODUTO)TT,
        DS_MARCA,
        UNIDADE_COMPRA,
        VL_UNITARIO,
        DS_SUB_CLA
FROM(   SELECT  DISTINCT P.DS_PRODUTO,
        P.CD_PRODUTO,
        IEL.DS_MARCA,
        D.DS_UNIDADE UNIDADE_COMPRA,
        D.VL_UNITARIO,
        SC.DS_SUB_CLA
FROM    DBAMV.PRODUTO P,
        DBAMV.SUB_CLAS SC,
        DBAMV.UNI_PRO UP,
        DBAMV.ITLOT_ENT IEL,
       (SELECT  DT_ENTRADA,
                IEP.CD_PRODUTO,
                DS_UNIDADE,
                IEP.VL_UNITARIO,
                IEP.CD_ITENT_PRO
        FROM    DBAMV.ENT_PRO EP,
                DBAMV.ITENT_PRO IEP,
                DBAMV.UNI_PRO UP
        WHERE   EP.CD_ENT_PRO = IEP.CD_ENT_PRO
          AND   IEP.CD_UNI_PRO = UP.CD_UNI_PRO)D
       
WHERE   TP_ATIVO = 'S'
  AND   SN_MOVIMENTACAO = 'S'
  AND   SN_BLOQUEIO_DE_COMPRA = 'N'
  AND   P.CD_CLASSE = SC.CD_CLASSE
  AND   P.CD_SUB_CLA = SC.CD_SUB_CLA
  AND   P.CD_ESPECIE = SC.CD_ESPECIE
  AND   P.CD_PRODUTO = UP.CD_PRODUTO
  AND   P.CD_PRODUTO = D.CD_PRODUTO
  AND   IEL.CD_ITENT_PRO = D.CD_ITENT_PRO
--  AND   P.CD_PRODUTO = 21725
  AND   D.DT_ENTRADA = (SELECT  MAX(EP.DT_ENTRADA)ULTIMA_ENTRADA
                        FROM    DBAMV.ENT_PRO EP,
                                DBAMV.ITENT_PRO IEP
                        WHERE   EP.CD_ENT_PRO = IEP.CD_ENT_PRO
                          AND   IEP.CD_PRODUTO = P.CD_PRODUTO)
/*GROUP
   BY   P.DS_PRODUTO,
        P.CD_PRODUTO,
        SC.DS_SUB_CLA,
        TRUNC(P.VL_ULTIMA_ENTRADA,2),
        P.DT_ULTIMA_ENTRADA   */                       
)

GROUP
   BY   DS_PRODUTO,
        CD_PRODUTO,
        DS_MARCA,
        UNIDADE_COMPRA,
        VL_UNITARIO,
        DS_SUB_CLA
        
HAVING  COUNT(CD_PRODUTO) = 1        

ORDER
   BY   COUNT(CD_PRODUTO) ASC 
;