/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 22/02/2024
TITULO: PORCENTAGEM DE PACIENTE RECONCILIADOS POR PACIENTES INTERNADOS
DESCRICAO: EXCETO PACIENTES INTERNADOS EM 24H
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:

OBS: 
 - DEVE SER REALIZADO FILTRO POR CONVÊNIO?
 

*/

SELECT  COUNT(A.CD_ATENDIMENTO)TOT

FROM    DBAMV.MOV_INT MI,
        DBAMV.ATENDIME A

WHERE   MI.CD_ATENDIMENTO = A.CD_ATENDIMENTO
  AND   MI.TP_MOV = 'I'
  AND   A.TP_ATENDIMENTO = 'I'
  AND   DT_MOV_INT NOT IN TO_DATE(SYSDATE)
  AND   TO_CHAR(A.DT_ATENDIMENTO,'MMYYYY') = '012024'
;


SELECT  COUNT(PDO.DS_DOCUMENTO)TOT,
        TO_CHAR(PDC.DH_REFERENCIA,'MMYYYY') DT

FROM    DBAMV.PW_DOCUMENTO_CLINICO PDC,
        DBAMV.PW_EDITOR_CLINICO PEC,
        DBAMV.PW_DOCUMENTO_OBJETO PDO,
        DBAMV.ATENDIME A

WHERE   PDC.CD_DOCUMENTO_CLINICO = PEC.CD_DOCUMENTO_CLINICO
  AND   PEC.CD_DOCUMENTO = PDO.CD_DOCUMENTO
  AND   PDC.CD_ATENDIMENTO = A.CD_ATENDIMENTO
  AND   PDO.CD_DOCUMENTO = 256
  AND   PDC.CD_TIPO_DOCUMENTO = 28
  AND   TO_CHAR(A.DT_ATENDIMENTO,'MMYYYY') = '012024'

GROUP
   BY   PDC.CD_ATENDIMENTO,
        PDC.DH_REFERENCIA

ORDER
   BY   PDC.DH_REFERENCIA  
;