/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 09/04/2023
TITULO: RELATÓRIO DE SUGENSTÃO DE COMPRAS
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT     ESTOQUE.DS_ESTOQUE
          ,ITMVTO_ESTOQUE.CD_PRODUTO
          ,PRODUTO.DS_PRODUTO DS_PRODUTO
          ,VERIF_DS_UNID_PROD(ITMVTO_ESTOQUE.CD_PRODUTO)  DS_UNIDADE
          ,SUM( (( ( ITMVTO_ESTOQUE.QT_MOVIMENTACAO * DECODE( MVTO_ESTOQUE.TP_MVTO_ESTOQUE, 'D', -1, 'C', -1,'N',-1, 1)  ) * UNI_PRO.VL_FATOR) / VERIF_VL_FATOR_PROD(ITMVTO_ESTOQUE.CD_PRODUTO)))   QT_CONS
          ,(SUM( ROUND( ( ITMVTO_ESTOQUE.QT_MOVIMENTACAO * DECODE( MVTO_ESTOQUE.TP_MVTO_ESTOQUE, 'D', -1, 'C', -1,'N' ,-1,1)  ) * UNI_PRO.VL_FATOR * VERIF_VL_CUSTO_MEDIO( ITMVTO_ESTOQUE.CD_PRODUTO, MVTO_ESTOQUE.DT_MVTO_ESTOQUE,'H', PRODUTO.VL_CUSTO_MEDIO, MVTO_ESTOQUE.HR_MVTO_ESTOQUE,1 ), 2 ) ) ) VL_UNIT
          ,EST_PRO.QT_ESTOQUE_ATUAL
		  ,ROUND(EST_PRO.QT_ESTOQUE_ATUAL/(SUM( (( ( ITMVTO_ESTOQUE.QT_MOVIMENTACAO * DECODE( MVTO_ESTOQUE.TP_MVTO_ESTOQUE, 'D', -1, 'C', -1,'N',-1, 1)  ) * UNI_PRO.VL_FATOR) / VERIF_VL_FATOR_PROD(ITMVTO_ESTOQUE.CD_PRODUTO)) )/60),2) EST_DIAS
		  ,((SUM((( ITMVTO_ESTOQUE.QT_MOVIMENTACAO * DECODE( MVTO_ESTOQUE.TP_MVTO_ESTOQUE, 'D', -1, 'C', -1,'N',-1, 1)  ) * UNI_PRO.VL_FATOR) / VERIF_VL_FATOR_PROD(ITMVTO_ESTOQUE.CD_PRODUTO))/60)*60)-EST_PRO.QT_ESTOQUE_ATUAL PREV_DIAS
		  
FROM      DBAMV.MVTO_ESTOQUE
         ,DBAMV.ITMVTO_ESTOQUE
         ,DBAMV.PRODUTO
         ,DBAMV.UNI_PRO
         ,DBAMV.EST_PRO
         ,DBAMV.ESTOQUE
		 
WHERE    MVTO_ESTOQUE.DT_MVTO_ESTOQUE BETWEEN TO_DATE('01/04/2024','DD/MM/YYYY') AND TO_DATE('30/04/2024','DD/MM/YYYY')
  AND    MVTO_ESTOQUE.CD_MVTO_ESTOQUE = ITMVTO_ESTOQUE.CD_MVTO_ESTOQUE
  AND    PRODUTO.CD_PRODUTO = ITMVTO_ESTOQUE.CD_PRODUTO
  AND    UNI_PRO.CD_UNI_PRO = ITMVTO_ESTOQUE.CD_UNI_PRO
  AND    EST_PRO.CD_PRODUTO = PRODUTO.CD_PRODUTO
  AND    EST_PRO.CD_ESTOQUE = ESTOQUE.CD_ESTOQUE
  AND    ESTOQUE.CD_ESTOQUE = MVTO_ESTOQUE.CD_ESTOQUE 
  AND    ESTOQUE.CD_MULTI_EMPRESA = 1
  AND    PRODUTO.CD_ESPECIE IN (1,2)
  AND    ESTOQUE.CD_ESTOQUE = '1'
  AND    MVTO_ESTOQUE.TP_MVTO_ESTOQUE IN ('S','P','D','C','T', 'X','R')
  AND    PRODUTO.SN_MOVIMENTACAO = 'S' 
  AND    PRODUTO.SN_BLOQUEIO_DE_COMPRA = 'N'
  --AND    PRODUTO.CD_PRODUTO = 12582
 
GROUP BY  ITMVTO_ESTOQUE.CD_PRODUTO
              ,PRODUTO.DS_PRODUTO
              ,PRODUTO.VL_CUSTO_MEDIO
              ,EST_PRO.QT_ESTOQUE_ATUAL
              ,ESTOQUE.CD_ESTOQUE
              ,ESTOQUE.DS_ESTOQUE
HAVING ((SUM((( ITMVTO_ESTOQUE.QT_MOVIMENTACAO * DECODE( MVTO_ESTOQUE.TP_MVTO_ESTOQUE, 'D', -1, 'C', -1,'N',-1, 1)  ) * UNI_PRO.VL_FATOR) / VERIF_VL_FATOR_PROD(ITMVTO_ESTOQUE.CD_PRODUTO))/60)*45)-EST_PRO.QT_ESTOQUE_ATUAL >= 0

ORDER BY  PRODUTO.DS_PRODUTO

