/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 01/02/2024
TITULO: QUANTITATIVO DE ITENS DISPENSADOS
DESCRICAO: QUANTITATIVO DE ITENS DISPENSADOS PELA FARMÁCIA MENSALMENTE
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT  Count(*)TOTAL
       ,To_Char(DT_SOLSAI_PRO,'MM/YYYY') DATA

FROM    DBAMV.SOLSAI_PRO SS
       ,DBAMV.ITSOLSAI_PRO ISS

WHERE   SS.CD_SOLSAI_PRO = ISS.CD_SOLSAI_PRO
  AND   SS.DT_SOLSAI_PRO BETWEEN To_Date('012023','MMYYYY')
                             AND To_Date('072023','MMYYYY')

  AND   SS.CD_ESTOQUE = 3
  AND   ISS.QT_ATENDIDA > 0
  AND   SS.CD_ATENDIMENTO IS NOT NULL

GROUP BY To_Char(DT_SOLSAI_PRO,'MM/YYYY');