/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 14/04/2024
TITULO: RELATÓRIO DE ULTIMA MOVIMENTAÇÃO DE ITENS ATIVOS
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL: JEFFERSON LIMA
DATA: 29/04/2024
MOTIVO: ACRESCIMO DE FILTRO POR ESTOQUE
DESCRIÇÃO:
*/

SELECT 	P.CD_PRODUTO,
        P.DS_PRODUTO,
        E.DS_ESTOQUE,
        EP.QT_ESTOQUE_ATUAL,
        FNC_MGES_CUSTO_MEDIO_PRODUTO(P.CD_PRODUTO, F.DT)CUSTO_MEDIO,
        F.DT DT_ULT_MOV,
        CASE
          WHEN  (TRUNC(SYSDATE) - TRUNC(TO_TIMESTAMP(F.DT))) >= 30
            THEN 'R'
          ELSE 'G'
        END DIF,
        P.SN_PADRONIZADO,
        P.SN_MESTRE,
        P.SN_MEDICAMENTO,
        P.SN_BLOQUEIA_MOVIMENTACAO
FROM   (SELECT  DISTINCT
                P.CD_PRODUTO,
                MAX(IME.CD_MVTO_ESTOQUE)CD_MVTO_ESTOQUE,
                Max(IME.DH_MVTO_ESTOQUE)DT
        FROM    DBAMV.MVTO_ESTOQUE ME,
                DBAMV.ITMVTO_ESTOQUE IME,
                DBAMV.PRODUTO P

        WHERE	ME.CD_MVTO_ESTOQUE = IME.CD_MVTO_ESTOQUE
          AND 	IME.CD_PRODUTO = P.CD_PRODUTO
          AND   P.CD_ESPECIE IN (1,2,3)
          AND   P.SN_MOVIMENTACAO = 'S'
	GROUP
    	   BY   P.CD_PRODUTO
	ORDER
	   BY   P.CD_PRODUTO)F,
        DBAMV.PRODUTO P,
        DBAMV.MVTO_ESTOQUE ME,
        DBAMV.ESTOQUE E,
        DBAMV.EST_PRO EP
WHERE	F.CD_PRODUTO = P.CD_PRODUTO
  AND 	F.CD_MVTO_ESTOQUE = ME.CD_MVTO_ESTOQUE
  AND   ME.CD_ESTOQUE = E.CD_ESTOQUE
  AND	E.CD_ESTOQUE = EP.CD_ESTOQUE
  AND   P.CD_PRODUTO = EP.CD_PRODUTO
  AND   E.DS_ESTOQUE LIKE ('%%');
