/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 14/03/2024
TITULO: RELATÓRIO DE ULTIMA MOVIMENTAÇÃO DE ITENS ATIVOS
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT 	DISTINCT
        IME.CD_ITMVTO_ESTOQUE, 
        P.CD_PRODUTO,
        MIN(IME.DH_MVTO_ESTOQUE)TST

FROM    DBAMV.MVTO_ESTOQUE ME,
		DBAMV.ITMVTO_ESTOQUE IME,
		DBAMV.PRODUTO P

WHERE	ME.CD_MVTO_ESTOQUE = IME.CD_MVTO_ESTOQUE
  AND 	IME.CD_PRODUTO = P.CD_PRODUTO
  AND   P.CD_ESPECIE IN (1,2,3)
  --AND   P.TP_ATIVO = 'S'
  AND   P.SN_MOVIMENTACAO = 'S'
  AND   P.CD_PRODUTO = 601

GROUP
   BY   IME.CD_ITMVTO_ESTOQUE, 
        P.CD_PRODUTO
;