/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 01/02/2024
TITULO: QUANTITATIVO DE PACIENTES POR DIA X MÊS
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT Count(NM_PACIENTE)TOTAL
     ,DATA

FROM(
SELECT
  P.NM_PACIENTE,
  To_Char(A.DT_ATENDIMENTO, 'DD/MM/YYYY') AS DATA
FROM
  DBAMV.ATENDIME A,
  DBAMV.PACIENTE P
WHERE
      A.DT_ATENDIMENTO BETWEEN To_Date('01012023', 'DDMMYYYY')
                       AND To_Date('31072023', 'DDMMYYYY')
  AND P.CD_PACIENTE = A.CD_PACIENTE
GROUP BY
  To_Char(A.DT_ATENDIMENTO, 'DD/MM/YYYY'),P.NM_PACIENTE
ORDER BY
  DATA
     )

GROUP BY
  DATA
ORDER BY
  To_Date(DATA,'DD/MM/YYYY')