/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 01/02/2024
TITULO: EXAMES DE IMAGENS GERADOS VIA ATENDIMENTO PA
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT  Count(IPR.CD_ITPED_RX) TOTAL

FROM
        DBAMV.ITPED_RX IPR
       ,DBAMV.PED_RX PR
       ,DBAMV.ATENDIME A
       ,DBAMV.ORI_ATE O

WHERE
        IPR.CD_PED_RX = PR.CD_PED_RX
  AND   A.CD_ATENDIMENTO = PR.CD_ATENDIMENTO
  AND   O.CD_ORI_ATE = A.CD_ORI_ATE

  AND   A.TP_ATENDIMENTO IN ('U')
  AND   A.DT_ATENDIMENTO BETWEEN To_Date('01/01/2023','DD/MM/YYYY')
                             AND To_Date(SYSDATE)
  AND   A.CD_ORI_ATE = 14
