SELECT
  Count(*) AS TOTAL_PA_ADT,
  To_Char(A.DT_ATENDIMENTO, 'MM/YYYY') AS DATA
FROM
  DBAMV.ATENDIME A
WHERE
  A.DT_ATENDIMENTO BETWEEN To_Date('01012023', 'DDMMYYYY')
                       AND To_Date('31072023', 'DDMMYYYY')

GROUP BY
  To_Char(A.DT_ATENDIMENTO, 'MM/YYYY')
ORDER BY
  To_Date(DATA,'MM/YYYY')
