/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 01/02/2024
TITULO: QUANTITATIVO DE PACIENTES POR DIA X MÊS
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT COUNT(NM_PACIENTE) TOTAL, 
       DATA,
	   DECODE(TP_ATENDIMENTO,'A', 'AMBULATORIAL', 'U', 'URGENCIA', 'E', 'EMERGENCIA', 'I', 'INTERNACAO') TP_ATENDIMENTO

  FROM (SELECT P.NM_PACIENTE,
			   TO_CHAR(A.DT_ATENDIMENTO, 'DD/MM/YYYY') AS DATA,
			   A.TP_ATENDIMENTO
		  FROM DBAMV.ATENDIME A, DBAMV.PACIENTE P
		 WHERE A.DT_ATENDIMENTO BETWEEN TO_DATE('01012023', 'DDMMYYYY') AND TO_DATE('31072023', 'DDMMYYYY')
		   AND P.CD_PACIENTE = A.CD_PACIENTE
		   AND A.CD_MULTI_EMPRESA = 1
		 GROUP BY TO_CHAR(A.DT_ATENDIMENTO, 'DD/MM/YYYY'), 
		          P.NM_PACIENTE,
				  A.TP_ATENDIMENTO)

 GROUP BY DATA,
          TP_ATENDIMENTO
 ORDER BY TO_DATE(DATA, 'DD/MM/YYYY')
