/*CREATED BY
NAME: JEFFERSON LIMA GONÇALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 21/02/2024
TITULO: PERCENTUAL DE SOLICITAÇÕES POR TOTAL
DESCRICAO: PORCENTAGEM DE SOLICITAÇÕES ATENDIDAS NO SISTEMA EM RELAÇÃO AO TOTAL DE SOLICITAÇÕES
FILTROS:
  - ESTOQUE / (3) = FARMACIA DISPENSACAO
  - ESTOQUE / (28) = FARMACIA CENTRO CIRURGICO
  - ESTOQUE / (45) FARMACIA UTI
  - DATA / ENTRE DATAS MÊS E ANO
  - EMPRESA / (1) = HOSPITAL UNIMED IMPERATRIZ
   
ÚLTIMA ATUALIZAÇÃO
RESPONSÁVEL: 
CARGO: 
DATA:
MOTIVO:
DESCRIÇÃO: 
*/

SELECT  COUNT(SSP.CD_SOLSAI_PRO)TOTAL_SOL,
        COUNT(SSP.CD_MOT_DEV) TOTAL_DEV,
        TRUNC((COUNT(SSP.CD_MOT_DEV) * 100) / COUNT(SSP.CD_SOLSAI_PRO),2) PERCENTUAL,
        TO_CHAR(SSP.DT_SOLSAI_PRO,'MM/YYYY') MES,
        E.DS_ESTOQUE

FROM    DBAMV.SOLSAI_PRO SSP,
        DBAMV.ESTOQUE E

WHERE   SSP.CD_ESTOQUE IN (3,28,45)
  AND   SSP.DT_CANCELAMENTO IS NULL
  AND   E.CD_MULTI_EMPRESA = 1
  AND   SSP.DT_SOLSAI_PRO BETWEEN TO_DATE('122023','MMYYYY') AND TO_DATE('022024','MMYYYY')

  AND   SSP.CD_ESTOQUE = E.CD_ESTOQUE

GROUP   
   BY   E.DS_ESTOQUE,
        TO_CHAR(SSP.DT_SOLSAI_PRO,'MM/YYYY')
;