/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 01/02/2024
TITULO: QUANTITATIVO DE ATENDIMENTOS
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT SUM(INTERNACOES),
       SUM(OBITO),
	   TRUNC((SUM(OBITO)/SUM(INTERNACOES)),4)*100 TX_OBITO
	   
FROM   (
SELECT  CD_ATENDIMENTO,
        DT_ALTA,
		CD_ATENDIMENTO_PAI

FROM    DBAMV.ATENDIME A,
        DBAMV.LEITO L

WHERE   A.CD_LEITO = L.CD_LEITO
  AND   L.CD_UNID_INT IN (2,11,26)
  AND   A.TP_ATENDIMENTO = 'I'
  AND   A.DT_ALTA IS NOT NULL
  AND   A.CD_ATENDIMENTO_PAI IS NULL
  AND   TO_CHAR(A.DT_ALTA,'MMYYYY') = 012024
  
UNION ALL

SELECT  0 INTERNACOES,
        COUNT(*)OBITO

FROM   DBAMV.ATENDIME A,
       DBAMV.MOT_ALT MA

WHERE  A.CD_MOT_ALT = MA.CD_MOT_ALT
  AND  TP_ATENDIMENTO = 'I'
  AND  MA.DS_MOT_ALT LIKE ('%OBITO%')
  AND  TO_CHAR(A.DT_ALTA,'MMYYYY') = 012024
       )
;
