/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 01/02/2024
TITULO: TAXA DE INTERNAÇÃO VIA PA MENSALMENTE
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT  TOTAL
       ,TOTAL_GERAL
       ,FULL
       ,Trunc((TOTAL/TOTAL_GERAL*100),2) || ' %' PERCENT
       ,DATA

FROM (
SELECT  TOTAL
       ,TOTAL_GERAL
       ,(TOTAL_GERAL - TOTAL) FULL
       ,F1.DATA

FROM (
SELECT  Count(*) TOTAL
       ,To_Char(A.DT_ATENDIMENTO,'MM/YYYY') DATA

FROM DBAMV.ATENDIME A
    ,DBAMV.PACIENTE P
    ,DBAMV.ORI_ATE O

WHERE A.CD_PACIENTE = P.CD_PACIENTE
AND   A.CD_ORI_ATE = O.CD_ORI_ATE

AND   A.DT_ATENDIMENTO BETWEEN To_Date('01/01/2023','DD/MM/YYYY')
                           AND To_Date('31/07/2023','DD/MM/YYYY')
AND   P.NM_PACIENTE NOT LIKE ('RN%')
AND   A.CD_PRO_INT IS NOT NULL
AND   A.TP_ATENDIMENTO IN ('I')
AND   A.CD_TIPO_INTERNACAO = 4

GROUP BY To_Char(A.DT_ATENDIMENTO,'MM/YYYY')

ORDER BY DATA)F1
,
(SELECT  Count(*)TOTAL_GERAL
             ,To_CHAR(A.DT_ATENDIMENTO,'MM/YYYY') DATA

      FROM    DBAMV.ATENDIME A
             ,DBAMV.PACIENTE P

      WHERE   A.DT_ATENDIMENTO BETWEEN To_Date('01/01/2023','DD/MM/YYYY')
                                  AND To_Date('31/07/2023','DD/MM/YYYY')
        AND   A.CD_PRO_INT IS NOT NULL
        AND   A.TP_ATENDIMENTO = ('I')

        AND   A.CD_PACIENTE = P.CD_PACIENTE

        GROUP BY To_Char(A.DT_ATENDIMENTO,'MM/YYYY')

        ORDER BY DATA)F2

WHERE F1.DATA = F2.DATA)
;