/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 01/02/2024
TITULO: CUSTOS COM PLANTÃO MEDICO POR MÊS
DESCRICAO: 
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT
        Trunc(Sum(RP.VL_REPASSE),2)TOTAL
       ,To_Char(R.DT_REPASSE,'MM/YYYY')DATA

FROM    DBAMV.REPASSE_PRESTADOR RP
       ,DBAMV.REPASSE R

WHERE   RP.CD_REPASSE = R.CD_REPASSE
  AND   R.DT_COMPETENCIA BETWEEN To_Date('012023','MMYYYY')
                             AND To_Date('072023','MMYYYY')

  AND   R.TP_REPASSE = 'M'
  AND   R.DS_REPASSE LIKE ('%PLAN%')

GROUP BY To_Char(R.DT_REPASSE,'MM/YYYY')

ORDER BY DATA