/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 25/01/2024
TITULO: AVALIAÇÃO E PARECER X FATURAMENTO (INTERNAÇÃO)
DESCRICAO: 
FILTROS:

ULTIMA ATUALIZAÇÃO
RESPONSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT  DISTINCT
        A.CD_ATENDIMENTO ATENDIMENTO,
        G.NR_GUIA GUIA,
        IRF.CD_PRO_FAT COD_PROCEDIMENTO,
        PF.DS_PRO_FAT DESC_PROCEDIMENTO,
        TO_CHAR(IRF.DT_LANCAMENTO,'DD/MM/YYYY') DATA_EXEC,
        IRF.VL_TOTAL_CONTA VALOR_PROCEDIMENTO,
        P.NM_PACIENTE NOME_PACIENTE,
        PRE.NM_PRESTADOR PRESTADOR_EXEC,
        C.NM_CONVENIO CONVENIO,
        S.NM_SETOR SETOR_EXEC
        

FROM    DBAMV.REG_FAT RF,
        DBAMV.ATENDIME A,
        DBAMV.PACIENTE P,
        DBAMV.ITREG_FAT IRF,
        DBAMV.PRO_FAT PF,
        DBAMV.SETOR S,
        DBAMV.CONVENIO C,
        DBAMV.PRESTADOR PRE,
        DBAMV.REMESSA_FATURA REM,
       (SELECT  DISTINCT SN_PAGA_PELO_CONVENIO,
                CD_PRESTADOR,
                CD_CONVENIO
        FROM    DBAMV.PRES_CON PC
        WHERE   CD_CONVENIO IN (3,4)
          AND   CD_MULTI_EMPRESA = 1) PC,
       (SELECT  DISTINCT NR_GUIA,
                CD_ATENDIMENTO
        FROM    DBAMV.GUIA
        WHERE   TP_GUIA = 'I') G
        
WHERE   A.CD_ATENDIMENTO = RF.CD_ATENDIMENTO
  AND   A.CD_PACIENTE = P.CD_PACIENTE
  AND   RF.CD_REG_FAT = IRF.CD_REG_FAT
  AND   IRF.CD_PRO_FAT = PF.CD_PRO_FAT
  AND   IRF.CD_PRESTADOR = PC.CD_PRESTADOR
  AND   RF.CD_CONVENIO = PC.CD_CONVENIO
  AND   IRF.CD_SETOR_PRODUZIU = S.CD_SETOR
  AND   A.CD_ATENDIMENTO = G.CD_ATENDIMENTO
  AND   RF.CD_CONVENIO = C.CD_CONVENIO
  AND   IRF.CD_PRESTADOR = PRE.CD_PRESTADOR
  AND   RF.CD_REMESSA = REM.CD_REMESSA
  
  AND   RF.CD_CONVENIO IN (3,4)
  AND   IRF.CD_PRO_FAT IN ('10101039','10102019','10102021','10102020')
  AND   IRF.VL_TOTAL_CONTA IN (350,315)
  AND   TO_CHAR(REM.DT_ENTREGA_DA_FATURA,'MMYYYY') = '102023'
  AND   PC.SN_PAGA_PELO_CONVENIO = 'N'
  AND   REM.SN_FECHADA = 'S';
