/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 25/01/2024
TITULO: AVALIAÇÃO E PARECER X FATURAMENTO (URGENCIA E AMBULATORIAL)
DESCRICAO: 
FILTROS:

ULTIMA ATUALIZAÇÃO
RESPONSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT  DISTINCT
        A.CD_ATENDIMENTO ATENDIMENTO,
        G.NR_GUIA GUIA,
        IRA.CD_PRO_FAT COD_PROCEDIMENTO,
        PF.DS_PRO_FAT DESC_PROCEDIMENTO,
        TO_CHAR(IRA.HR_LANCAMENTO,'DD/MM/YYYY') DATA_EXEC,
        IRA.VL_TOTAL_CONTA VALOR_PROCEDIMENTO,
        P.NM_PACIENTE NOME_PACIENTE,
        PRE.NM_PRESTADOR PRESTADOR_EXECUTANTE,
        C.NM_CONVENIO,                               
        S.NM_SETOR
        

FROM    DBAMV.REG_AMB RA,
        DBAMV.ATENDIME A,
        DBAMV.PACIENTE P,
        DBAMV.ITREG_AMB IRA,
        DBAMV.PRO_FAT PF,
        DBAMV.PRESTADOR PRE,
        DBAMV.SETOR S,
        DBAMV.CONVENIO C,
        DBAMV.REMESSA_FATURA REM,
       (SELECT  DISTINCT SN_PAGA_PELO_CONVENIO,
                CD_PRESTADOR,
                CD_CONVENIO
        FROM    DBAMV.PRES_CON PC
        WHERE   CD_CONVENIO IN (3,4)
          AND   CD_MULTI_EMPRESA = 1) PC,
       (SELECT  DISTINCT NR_GUIA,
                CD_ATENDIMENTO
        FROM    DBAMV.GUIA
        WHERE   TP_GUIA = 'C') G

WHERE   A.CD_ATENDIMENTO = IRA.CD_ATENDIMENTO
  AND   A.CD_PACIENTE = P.CD_PACIENTE
  AND   RA.CD_REG_AMB = IRA.CD_REG_AMB
  AND   IRA.CD_PRO_FAT = PF.CD_PRO_FAT
  AND   IRA.CD_PRESTADOR = PRE.CD_PRESTADOR
  AND   IRA.CD_SETOR_PRODUZIU = S.CD_SETOR
  AND   RA.CD_CONVENIO = PC.CD_CONVENIO
  AND   PRE.CD_PRESTADOR = PC.CD_PRESTADOR
  AND   RA.CD_CONVENIO = C.CD_CONVENIO
  AND   A.CD_ATENDIMENTO = G.CD_ATENDIMENTO
  AND   RA.CD_REMESSA = REM.CD_REMESSA
  
  AND   RA.CD_CONVENIO IN (3,4)
  AND   IRA.CD_PRO_FAT IN ('10101039','10102019','10102021','10102020')
  AND   IRA.VL_TOTAL_CONTA IN ('350','315')
  AND   TO_CHAR(REM.DT_ENTREGA_DA_FATURA,'MMYYYY') = '102023'
  AND   PC.SN_PAGA_PELO_CONVENIO = 'S'
  AND   REM.SN_FECHADA = 'S'
;