/*CREATED BY
NAME: JEFFERSON LIMA GONCALVES
CARGO: ANALISTA E DESENVOLVEDOR DE SISTEMAS JR
DATA: 18/03/2024
TITULO: CONTAS FECHADAS POR FATURISTAS
DESCRICAO: Relatório personalizado que me informe os seguintes dados: quanto cada faturista produz em média, e saber quantitativo de contas na produção diária.
FILTROS:

ÚLTIMA ATUALIZAÇÃO
RESPÓNSAVEL:
DATA:
MOTIVO:
DESCRIÇÃO:
*/

SELECT	*

FROM   (SELECT	DISTINCT
				RG.CD_ATENDIMENTO,
				P.NM_PACIENTE,
				RG.VL_TOTAL_CONTA,
				RG.DT_FECHAMENTO,
				RG.NM_USUARIO_FECHOU,
				C.NM_CONVENIO,
				TO_CHAR('INT') TP_CONTA

		FROM	DBAMV.REG_FAT RG,
				DBAMV.ATENDIME A,
				DBAMV.CONVENIO C,
				DBAMV.PACIENTE P

		WHERE	RG.CD_ATENDIMENTO = A.CD_ATENDIMENTO
		  AND   RG.CD_CONVENIO = C.CD_CONVENIO
		  AND   A.CD_PACIENTE = P.CD_PACIENTE
		
		  AND 	RG.SN_FECHADA = 'S'
		  AND 	TO_CHAR(RG.DT_FECHAMENTO,'MMYYYY') = '012024'
		  AND	RG.CD_MULTI_EMPRESA = 1					

		UNION 	ALL

		SELECT	DISTINCT
				IRA.CD_ATENDIMENTO,
				P.NM_PACIENTE,
				RA.VL_TOTAL_CONTA,
				RA.DT_LANCAMENTO_FINAL,
				IRA.NM_USUARIO_FECHOU,
				C.NM_CONVENIO,
				TO_CHAR('AMB') TP_CONTA

		FROM	DBAMV.REG_AMB RA,
				DBAMV.ITREG_AMB IRA,
				DBAMV.ATENDIME A,
				DBAMV.CONVENIO C,
				DBAMV.PACIENTE P

		WHERE	IRA.CD_ATENDIMENTO = A.CD_ATENDIMENTO
		  AND   RA.CD_CONVENIO = C.CD_CONVENIO
		  AND 	RA.CD_REG_AMB = IRA.CD_REG_AMB
		  AND 	A.CD_PACIENTE = P.CD_PACIENTE
				
		  AND 	RA.SN_FECHADA = 'S'
		  AND 	RA.CD_MULTI_EMPRESA = '1'
		  AND 	TO_CHAR(DT_LANCAMENTO_FINAL,'MMYYYY') = '012024')
WHERE	TP_CONTA = 'AMB'		  
ORDER
   BY	4;